name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g., v9.0.0_1.0)宝塔版本+构建版本'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
            ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 构建 baota:minimal
    - name: Build minimal image
      run: |
        docker build -t eyunzhu/baota:minimal -t eyunzhu/baota:latest -t eyunzhu/baota:minimal-${{ github.event.inputs.image_tag }} -f ./dockerfiles/dockerfile.baota . || exit 1

    # 验证 baota:minimal 是否存在
    - name: Verify images exist
      run: |
        if ! docker image inspect eyunzhu/baota:minimal > /dev/null 2>&1; then
            echo "Error: eyunzhu/baota:minimal does not exist!"
            exit 1
        fi
    
    # 构建 baota:lnmp
    - name: Build lnmp image
      run: |
        docker build -t eyunzhu/baota:lnmp -t eyunzhu/baota:lnmp-${{ github.event.inputs.image_tag }} -f ./dockerfiles/dockerfile.baota-lnmp . || exit 1

    # 验证 baota:lnmp 是否存在
    - name: Verify images exist
      run: |
        if ! docker image inspect eyunzhu/baota:lnmp > /dev/null 2>&1; then
            echo "Error: eyunzhu/baota:lnmp does not exist!"
            exit 1
        fi
           
    - name: Push minimal image to Docker Hub
      run: |
        docker push eyunzhu/baota:minimal
        docker push eyunzhu/baota:latest
        docker push eyunzhu/baota:minimal-${{ github.event.inputs.image_tag }}

    - name: Push LNMP image to Docker Hub
      run: |
        docker push eyunzhu/baota:lnmp
        docker push eyunzhu/baota:lnmp-${{ github.event.inputs.image_tag }}